# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe4efc1b4c858fe3dcb8b66791264bda99b481698828409d9d42680236bd1fc32a723f68fb91428580c86aee7773dee07210783e92480d0b076f44cfbf3a136b

test:
  secret_key_base: 3b2dbcb4610c1ae72b42516829e6b77348414abd86e583cb6c4ebddbdad10ec1e229918fec141c319ef3af737407058591d6d78a5da384e8176589a480104fac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
